name: spotify-ai-playlist-generator
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.10
  - aiosignal=1.3.1
  - annotated-types=0.7.0
  - anyio=4.6.2.post1
  - async-timeout=4.0.3
  - attrs=24.2.0
  - blinker=1.6.2
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - click=8.1.7
  - deprecated=1.2.13
  - exceptiongroup=1.2.2
  - flask=3.0.3
  - flask_cors=4.0.0
  - frozenlist=1.5.0
  - greenlet=3.1.1
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.6
  - httpx=0.27.2
  - hyperframe=6.0.1
  - idna=3.10
  - importlib-metadata=7.0.1
  - itsdangerous=2.2.0
  - jinja2=3.1.4
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - langchain=0.3.4
  - langchain-core=0.3.13
  - langchain-text-splitters=0.3.0
  - langsmith=0.1.129
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=19.1.2
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.28
  - libsqlite=3.47.0
  - libzlib=1.3.1
  - llvm-openmp=19.1.2
  - markupsafe=2.1.3
  - multidict=6.1.0
  - ncurses=6.5
  - numpy=1.26.4
  - openssl=3.3.2
  - orjson=3.10.10
  - packaging=24.1
  - pip=24.2
  - propcache=0.2.0
  - pycparser=2.22
  - pydantic=2.9.2
  - pydantic-core=2.23.4
  - pysocks=1.7.1
  - python=3.12.7
  - python-dotenv=1.0.1
  - python_abi=3.12
  - pyyaml=6.0.2
  - readline=8.2
  - redis-py=4.3.4
  - requests=2.32.3
  - setuptools=75.1.0
  - six=1.16.0
  - sniffio=1.3.1
  - spotipy=2.23.0
  - sqlalchemy=2.0.36
  - tenacity=8.5.0
  - tk=8.6.13
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - urllib3=2.2.3
  - werkzeug=3.0.3
  - wheel=0.44.0
  - wrapt=1.14.1
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.16.0
  - zipp=3.20.2
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - langchain-ollama==0.2.0
      - ollama==0.3.3
